#eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# refresh actuator endpoint
management.endpoints.web.exposure.include=refresh

# zipkin
management.tracing.sampling.probability=1.0
