# Eureka config - use Docker service name.
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka

# Zipkin - use Docker service name.
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
