# DB configuration - use Docker database service name.
spring.datasource.url=jdbc:postgresql://product-db:5432/Product_Prod
spring.datasource.username=PROD_USER
spring.datasource.password=PROD_PASSWORD
