spring.application.name=inventory-service

server.servlet.context-path=/inventory
server.port=9010

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/inventoryDB
spring.datasource.username=shubhgaur
spring.datasource.password=password

#
spring.jpa.hibernate.ddl-auto=create-drop

# for console logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# This property should NOT be present in the Config Server's Git repository.
# It is used by a Config Client to fetch external configuration from the
# Config Server. Adding it at the repository level can cause configuration
# loading to recursively call the Config Server.
#spring.config.import=configserver:http://localhost:8888

