# DB configuration - use Docker database service name.
spring.datasource.url=jdbc:postgresql://orders-db:5432/Orders_Prod
spring.datasource.username=PROD_USER
spring.datasource.password=PROD_PASSWORD
